spring.application.name=chatbot
spring.datasource.url=jdbc:postgresql://db:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

ai.service.client.retry.max=3
ai.service.client.retry.delay-ms=1000
ai.service.client.endpoint="/ask"